/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JOptionPane;
import logica.Operaciones;

/**
 *
 * @author Vinni
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.opDecimalIN.setSelected(true);
        this.opBinariolOUT.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoIn = new javax.swing.ButtonGroup();
        grupoOut = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        opOctalOUT = new javax.swing.JRadioButton();
        opDecimalOUT = new javax.swing.JRadioButton();
        opBinariolOUT = new javax.swing.JRadioButton();
        opHexaOUT = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cjRespuesta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cjNumeroEntrada = new javax.swing.JTextField();
        btProcesar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        opOctalN = new javax.swing.JRadioButton();
        opDecimalIN = new javax.swing.JRadioButton();
        opBinariolIN = new javax.swing.JRadioButton();
        opHexaIN = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Resultado: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 390, 230, 30);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(null);

        grupoOut.add(opOctalOUT);
        opOctalOUT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        opOctalOUT.setText("Decimal");
        jPanel1.add(opOctalOUT);
        opOctalOUT.setBounds(20, 110, 110, 23);

        grupoOut.add(opDecimalOUT);
        opDecimalOUT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        opDecimalOUT.setText("Decimal");
        jPanel1.add(opDecimalOUT);
        opDecimalOUT.setBounds(20, 20, 110, 25);

        grupoOut.add(opBinariolOUT);
        opBinariolOUT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        opBinariolOUT.setText("Binario");
        jPanel1.add(opBinariolOUT);
        opBinariolOUT.setBounds(20, 50, 110, 23);

        grupoOut.add(opHexaOUT);
        opHexaOUT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        opHexaOUT.setText("Hexadecimal");
        opHexaOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opHexaOUTActionPerformed(evt);
            }
        });
        jPanel1.add(opHexaOUT);
        opHexaOUT.setBounds(20, 80, 110, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(370, 130, 150, 150);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DISEÑADO POR GIOVANNI BRICEÑO : VINNI9@GAMAIL.COM 2023");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 450, 790, 10);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Destino");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(340, 90, 180, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Origen");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 90, 180, 30);

        cjRespuesta.setBackground(new java.awt.Color(204, 204, 255));
        cjRespuesta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cjRespuesta.setEnabled(false);
        cjRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cjRespuestaActionPerformed(evt);
            }
        });
        getContentPane().add(cjRespuesta);
        cjRespuesta.setBounds(280, 390, 290, 28);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Digite el numero en base: ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 340, 230, 30);

        cjNumeroEntrada.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cjNumeroEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cjNumeroEntradaActionPerformed(evt);
            }
        });
        getContentPane().add(cjNumeroEntrada);
        cjNumeroEntrada.setBounds(280, 340, 290, 28);

        btProcesar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btProcesar.setForeground(new java.awt.Color(204, 0, 0));
        btProcesar.setText("PROCESAR");
        btProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProcesarActionPerformed(evt);
            }
        });
        getContentPane().add(btProcesar);
        btProcesar.setBounds(590, 340, 150, 31);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(null);

        grupoIn.add(opOctalN);
        opOctalN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        opOctalN.setText("Decimal");
        jPanel3.add(opOctalN);
        opOctalN.setBounds(20, 110, 110, 23);

        grupoIn.add(opDecimalIN);
        opDecimalIN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        opDecimalIN.setText("Decimal");
        jPanel3.add(opDecimalIN);
        opDecimalIN.setBounds(20, 20, 110, 25);

        grupoIn.add(opBinariolIN);
        opBinariolIN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        opBinariolIN.setText("Binario");
        jPanel3.add(opBinariolIN);
        opBinariolIN.setBounds(20, 50, 110, 23);

        grupoIn.add(opHexaIN);
        opHexaIN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        opHexaIN.setText("Hexadecimal");
        opHexaIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opHexaINActionPerformed(evt);
            }
        });
        jPanel3.add(opHexaIN);
        opHexaIN.setBounds(20, 80, 110, 23);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(110, 130, 150, 150);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Sistemas numéricos");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(200, 20, 260, 30);

        setSize(new java.awt.Dimension(807, 503));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cjRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cjRespuestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cjRespuestaActionPerformed

    private void cjNumeroEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cjNumeroEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cjNumeroEntradaActionPerformed

    private void btProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProcesarActionPerformed
        // TODO add your handling code here:
        procesar();
    }//GEN-LAST:event_btProcesarActionPerformed

    private void opHexaOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opHexaOUTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opHexaOUTActionPerformed

    private void opHexaINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opHexaINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opHexaINActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btProcesar;
    private javax.swing.JTextField cjNumeroEntrada;
    private javax.swing.JTextField cjRespuesta;
    private javax.swing.ButtonGroup grupoIn;
    private javax.swing.ButtonGroup grupoOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton opBinariolIN;
    private javax.swing.JRadioButton opBinariolOUT;
    private javax.swing.JRadioButton opDecimalIN;
    private javax.swing.JRadioButton opDecimalOUT;
    private javax.swing.JRadioButton opHexaIN;
    private javax.swing.JRadioButton opHexaOUT;
    private javax.swing.JRadioButton opOctalN;
    private javax.swing.JRadioButton opOctalOUT;
    // End of variables declaration//GEN-END:variables

    private void procesar() {
        Operaciones operaciones = new Operaciones();
        if (this.cjNumeroEntrada.getText().isEmpty()){
            this.generarMensajeWarning("No hay numero de entrada");
            return ;
        }
        if (this.opDecimalIN.isSelected() && this.opDecimalOUT.isSelected()){
            
        }
        
    }
    private void generarMensajeOk(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje, "Información", JOptionPane.INFORMATION_MESSAGE);
    }
    private void generarMensajeWarning(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje, "Información", JOptionPane.WARNING_MESSAGE);
    }
}
